language: python
sudo: false

cache:
  directories:
    - $HOME/.pip-cache/

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.3"
      env: TOXENV=py33 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.4"
      env: TOXENV=py34 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "3.5"
      env: TOXENV=py35 PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
    - python: "2.7"
      env: TOXENV=docs PIP_DOWNLOAD_CACHE=$HOME/.pip-cache

install:
- virtualenv --version
- git config --global user.email "travisci@jasonantman.com"
- git config --global user.name "travisci"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version
script:
  - tox -r

after_success:
  - codecov

notifications:
  email:
    on_success: always
    on_failure: always
  pushover:
    users:
    - secure: "SA0nU9p4+7+qBPLtijwmiAJXwx4hEWxyA+qnJ4jTTYD+XWmli479DIC6oiiyvSpYDDolthBf6D3mcEM1V3zMWE9mP5SCGEK+oj/vloLBT8XAV1nhedS4HXgOIqacIAstN4WmURLOBZfrMUF27UlAJ257wPCdD7DHcu8dNnUXAt6alK2PPFdz126UkN3PjTHPqRgVk0YuT6nz2d9ugbgvyp6ljDt1raf8hTy2h9GgrF2nxr3+H5o4cKf28HNQd0y4kFzRUVJ3B+lhYkPnc/JjFGRQYDncTVgAmY2DjXR0LX+Dn074WC2NsDL4mb2cTtmDoudkx02JCVeKOG1646faS1gQyMJAgrelFIcVmGfdJMIDODfX2/g3tRS5zbEF6RuLKb75BaKaV6w1FjX9vyB1f75kHkAZfVrmofkz0A2lH2sR94XhDP2oZOlgCP9NvZtoc2TYVz8XxWrYcIqesE06ILVwYHcH6E0atiDAJLzBPFnlcxj1T4o1JsE+NhsEhJnU+GHuiF+OoMEkDkdmzLIdR3Fy41+JLWwE6ujS3ZaOQNonWeI8bTZNjNbPCD8MQdE1K86gqNQYGyyB7ZDbLQZcj3nXGdNJiTHXCoyg1tniNRRdh/BcBPSV5PQnjLfukBtB3Fuldm1WP2wt4QitBULKtkrRf5SeIJNOph3cU2EKpV8="
    api_key:
      secure: "hxa8cZjs4VskXYaO28pz5DUEBdJK61MseRJ11HS7fNU5xZ1LCGxqIc86k7ekzk9/R4p6tF3QtdgK6BDAOawOa15IetX0MqbKrSHVxJ34l2i1xnRnU8LZpZAwFh/ZzQ58B/vRWouu2oCWDnQGM4jkYEeD+GJXofV+CkCAmB4ut0ujvps9eD5GIGzlzZZ0WV4B1KTeRhOLcqT5ch/GfkDHKBb6QXLKP27yufifuwoBjTahsPnzVfL6enFlQP/1lFidW2P/Jpd92uTdQsp0EkiLsjaWhyAWB1o7i+QKnEhxDlOaM3Dh6tofGh0J4KIbKX6+qxvQ9cHr829NebyLiuJTdSY4sSfsxavKZHBEc1vKoAPNtG1E6reXPKD5lZi/UQsMGB56AIuVn+IZ0fvNKex558WZKfi/ebUbdyskT1p4l8aYPT4mQ69tp8SRcG9a5nHB32aXc5gCAEHrtsWuT0peZx34G2ifj4aqUEnKvlbvJ4ALlrC9HfuVsn3g4hCflF3G2IHdogvgkA9NWg6RA7moKJCkRDSx0GnozcaAcmntnUckBMjrB6VQWN/Bd1qQX5m96/IwSHWtRERRTB2bVwWX0UtNZ3N+ZNgEUQYQnZk4NSP6xRj8RDt+KP2zmP8QnsETl4Ry0t0QMB9YO04Bwih6o7gTCVa1Wj8a+kemC+a8A6w="
branches:
  except:
    - "/^noci-.*$/"
